---
- hosts: localhost
  become: true
  vars:
    - terraform_version: "0.11.7"
    - rvm1_rubies: ['ruby-2.4.4']
    - rvm1_user: 'vagrant'
  roles:
  - secfigo.terraform        
  - rvm_io.ruby
        

 